//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G2_PVFAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities6 : DbContext
    {
        public Entities6()
            : base("name=Entities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Knowledge> Knowledges { get; set; }
        public virtual DbSet<Manufacture> Manufactures { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderLine> OrderLines { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Production> Productions { get; set; }
        public virtual DbSet<Productline> Productlines { get; set; }
        public virtual DbSet<Raw_Material> Raw_Materials { get; set; }
        public virtual DbSet<Sales_Person> Sales_people { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Supply> Supplies { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<Work_center> Work_centers { get; set; }
    }
}
